name: Scheduled Ping

on:
  schedule:
    - cron: '0 */7 * * *'  # Каждые 10 часов (в 00:00, 10:00, 20:00 UTC)

jobs:
  pinger_job:
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.APP_URL }}
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
